#!/bin/sh --plot 
python3 /Users/miltr339/work/PhD_code/PhD_chapter1/src/repeatmasker_window_analysis.py --masker_outfile /Users/miltr339/work/repeatmasking/repeat_gffs/A_obtectus_masking.ori.out --masker_out_gff /Users/miltr339/work/repeatmasking/repeat_gffs/A_obtectus_repeats.out.gff --annotation_gff /Users/miltr339/work/native_annotations/all_native_annot/A_obtectus_annotation_isoform_filtered.gff --annotation_gff2 /Users/miltr339/work/orthoDB_annotations/A_obtectus_braker_isoform_filtered.gff --window_length 2e6 --merge_gene_windows 1 --verbose --plot 
python3 /Users/miltr339/work/PhD_code/PhD_chapter1/src/repeatmasker_window_analysis.py --masker_outfile /Users/miltr339/work/repeatmasking/repeat_gffs/A_verrucosus_masking.ori.out --masker_out_gff /Users/miltr339/work/repeatmasking/repeat_gffs/A_verrucosus_repeats.out.gff --window_length 1e5 --merge_gene_windows 2 --verbose --plot 
python3 /Users/miltr339/work/PhD_code/PhD_chapter1/src/repeatmasker_window_analysis.py --masker_outfile /Users/miltr339/work/repeatmasking/repeat_gffs/B_siliquastri_masking.ori.out --masker_out_gff /Users/miltr339/work/repeatmasking/repeat_gffs/B_siliquastri_repeats.out.gff --annotation_gff /Users/miltr339/work/native_annotations/all_native_annot/B_siliquastri_annotation_isoform_filtered.gff --annotation_gff2 /Users/miltr339/work/orthoDB_annotations/B_siliquastri_braker_isoform_filtered.gff --window_length 1e6 --merge_gene_windows 2 --verbose --plot 
python3 /Users/miltr339/work/PhD_code/PhD_chapter1/src/repeatmasker_window_analysis.py --masker_outfile /Users/miltr339/work/repeatmasking/repeat_gffs/C_analis_masking.ori.out --masker_out_gff /Users/miltr339/work/repeatmasking/repeat_gffs/C_analis_repeats.out.gff --window_length 1e5 --merge_gene_windows 2 --verbose --plot 
python3 /Users/miltr339/work/PhD_code/PhD_chapter1/src/repeatmasker_window_analysis.py --masker_outfile /Users/miltr339/work/repeatmasking/repeat_gffs/C_chinensis_masking.ori.out --masker_out_gff /Users/miltr339/work/repeatmasking/repeat_gffs/C_chinensis_repeats.out.gff --window_length 1e5 --merge_gene_windows 2 --verbose --plot 
python3 /Users/miltr339/work/PhD_code/PhD_chapter1/src/repeatmasker_window_analysis.py --masker_outfile /Users/miltr339/work/repeatmasking/repeat_gffs/C_maculatus_masking.ori.out --masker_out_gff /Users/miltr339/work/repeatmasking/repeat_gffs/C_maculatus_repeats.out.gff --annotation_gff /Users/miltr339/work/native_annotations/all_native_annot/C_maculatus_annotation_isoform_filtered.gff --annotation_gff2 /Users/miltr339/work/orthoDB_annotations/C_maculatus_braker_isoform_filtered.gff --window_length 1e6 --merge_gene_windows 5 --verbose --plot 
python3 /Users/miltr339/work/PhD_code/PhD_chapter1/src/repeatmasker_window_analysis.py --masker_outfile /Users/miltr339/work/repeatmasking/repeat_gffs/C_septempunctata_masking.ori.out --masker_out_gff /Users/miltr339/work/repeatmasking/repeat_gffs/C_septempunctata_repeats.out.gff --annotation_gff /Users/miltr339/work/native_annotations/all_native_annot/C_septempunctata_annotation_isoform_filtered.gff --annotation_gff2 /Users/miltr339/work/orthoDB_annotations/C_septempunctata_braker_isoform_filtered.gff --window_length 1e6 --merge_gene_windows 2 --verbose --plot 
python3 /Users/miltr339/work/PhD_code/PhD_chapter1/src/repeatmasker_window_analysis.py --masker_outfile /Users/miltr339/work/repeatmasking/repeat_gffs/D_melanogaster_masking.ori.out --masker_out_gff /Users/miltr339/work/repeatmasking/repeat_gffs/D_melanogaster_repeats.out.gff --annotation_gff /Users/miltr339/work/native_annotations/all_native_annot/D_melanogaster_annotation_isoform_filtered.gff --annotation_gff2 /Users/miltr339/work/orthoDB_annotations/D_melanogaster_braker_isoform_filtered.gff --window_length 5e5 --merge_gene_windows 2 --verbose --plot 
python3 /Users/miltr339/work/PhD_code/PhD_chapter1/src/repeatmasker_window_analysis.py --masker_outfile /Users/miltr339/work/repeatmasking/repeat_gffs/D_ponderosae_masking.ori.out --masker_out_gff /Users/miltr339/work/repeatmasking/repeat_gffs/D_ponderosae_repeats.out.gff --annotation_gff /Users/miltr339/work/native_annotations/all_native_annot/D_ponderosae_annotation_isoform_filtered.gff --annotation_gff2 /Users/miltr339/work/orthoDB_annotations/D_ponderosae_braker_isoform_filtered.gff --window_length 5e5 --merge_gene_windows 2 --verbose --plot 
python3 /Users/miltr339/work/PhD_code/PhD_chapter1/src/repeatmasker_window_analysis.py --masker_outfile /Users/miltr339/work/repeatmasking/repeat_gffs/I_luminosus_masking.ori.out --masker_out_gff /Users/miltr339/work/repeatmasking/repeat_gffs/I_luminosus_repeats.out.gff --window_length 1e5 --merge_gene_windows 2 --verbose --plot 
python3 /Users/miltr339/work/PhD_code/PhD_chapter1/src/repeatmasker_window_analysis.py --masker_outfile /Users/miltr339/work/repeatmasking/repeat_gffs/P_pyralis_masking.ori.out --masker_out_gff /Users/miltr339/work/repeatmasking/repeat_gffs/P_pyralis_repeats.out.gff --annotation_gff /Users/miltr339/work/native_annotations/all_native_annot/P_pyralis_annotation_isoform_filtered.gff --annotation_gff2 /Users/miltr339/work/orthoDB_annotations/P_pyralis_braker_isoform_filtered.gff --window_length 1e6 --merge_gene_windows 2 --verbose --plot 
python3 /Users/miltr339/work/PhD_code/PhD_chapter1/src/repeatmasker_window_analysis.py --masker_outfile /Users/miltr339/work/repeatmasking/repeat_gffs/R_ferrugineus_masking.ori.out --masker_out_gff /Users/miltr339/work/repeatmasking/repeat_gffs/R_ferrugineus_repeats.out.gff --window_length 1e5 --verbose --plot 
python3 /Users/miltr339/work/PhD_code/PhD_chapter1/src/repeatmasker_window_analysis.py --masker_outfile /Users/miltr339/work/repeatmasking/repeat_gffs/T_castaneum_masking.ori.out --masker_out_gff /Users/miltr339/work/repeatmasking/repeat_gffs/T_castaneum_repeats.out.gff --annotation_gff /Users/miltr339/work/native_annotations/all_native_annot/T_castaneum_annotation_isoform_filtered.gff --annotation_gff2 /Users/miltr339/work/orthoDB_annotations/T_castaneum_braker_isoform_filtered.gff --window_length 1e6 --merge_gene_windows 1 --verbose --plot 
python3 /Users/miltr339/work/PhD_code/PhD_chapter1/src/repeatmasker_window_analysis.py --masker_outfile /Users/miltr339/work/repeatmasking/repeat_gffs/T_molitor_masking.ori.out --masker_out_gff /Users/miltr339/work/repeatmasking/repeat_gffs/T_molitor_repeats.out.gff --annotation_gff /Users/miltr339/work/native_annotations/all_native_annot/T_molitor_annotation_isoform_filtered.gff --annotation_gff2 /Users/miltr339/work/orthoDB_annotations/T_molitor_braker_isoform_filtered.gff --window_length 1e6 --merge_gene_windows 1 --verbose --plot 
python3 /Users/miltr339/work/PhD_code/PhD_chapter1/src/repeatmasker_window_analysis.py --masker_outfile /Users/miltr339/work/repeatmasking/repeat_gffs/Z_morio_masking.ori.out --masker_out_gff /Users/miltr339/work/repeatmasking/repeat_gffs/Z_morio_repeats.out.gff --annotation_gff /Users/miltr339/work/native_annotations/all_native_annot/Z_morio_annotation_isoform_filtered.gff --annotation_gff2 /Users/miltr339/work/orthoDB_annotations/Z_morio_braker_isoform_filtered.gff --window_length 1e6 --merge_gene_windows 2 --verbose --plot 
python3 /Users/miltr339/work/PhD_code/PhD_chapter1/src/repeatmasker_window_analysis.py --masker_outfile /Users/miltr339/work/repeatmasking/repeat_gffs/C_maculatus_superscaffolded_masking.ori.out --masker_out_gff /Users/miltr339/work/repeatmasking/repeat_gffs/C_maculatus_superscaffolded_repeats.out.gff --annotation_gff /Users/miltr339/work/native_annotations/all_native_annot/C_mac_superscaffolded_liftover_annotation.gff --annotation_gff2 /Users/miltr339/work/orthoDB_annotations/C_maculatus_superscaffolded_annotation_isoform_filtered.gff --window_length 3e6 --merge_gene_windows 2 --verbose --plot